config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do 
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments 
  end
  
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    acts_as_votable
    belongs_to:user
    has_many:comments,dependent: :destroy
    has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many:posts
  has_many:comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id
        @comment.post_id = @post.id
            
        if @comment.save
           redirect_to post_path(@post)
        else 
           render "new"
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
    before_action :authenticate_user!, except: [:index,:show]
    
    def index
        @posts = Post.all.order("created_at DESC")
    end
    
    def show
        @comments = Comment.where(post_id: @post)
    end
    
    def new
        @post = current_user.posts.build
    end
    

    def create
        @post = current_user.posts.build(post_params)
        
        if @post.save
            redirect_to @post
        else
            render "new"
        end
    end
    
    def edit
    end
    
    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render "edit"
        end
    end
    
    def destroy
        @post.destroy
        redirect_to root_path
    end
    
    def upvote
        @post.upvote_by current_user
        redirect_back(fallback_location: root_path)
    end
    
    def downvote
        @post.downvote_by current_user
        redirect_back(fallback_location: root_path)
    end
    
    
    private
    
    def find_post
        @post = Post.find(params[:id])
    end
    
    def post_params
        params.require(:post).permit(:title,:link,:description,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
   <p>コメント欄:<%= f.text_field :content %></p>
   <p><%= f.button :submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twelve</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%= link_to "ホーム",root_path %>
    <% if user_signed_in? %>
      <%= link_to current_user.name,edit_user_registration_path %>
      <%= link_to "新規投稿",new_post_path %>
    <% else %>
      <%= link_to "サインイン",new_user_session_path %>
      <%= link_to "新規ユーザー登録",new_user_registration_path %>
    <% end %>
  </header>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
　 <p>image:<%= f.file_field :image %></p>
   <p>titl:<%= f.text_field :title %></p>
   <p>link:<%= f.text_field :link %></p>
   <p>description:<%= f.text_field :description %></p>
   <p><%= f.button :submit %></p>
<% end %>






 

app/views/posts/edit.html.erb
<h1>編集<h1>
<%= render "posts/form"%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<p>===========================</p>
<!--postはpost.showへ行く-->
<%= link_to (image_tag post.image.url(:small)),post %>
<p><%= link_to post.title,post %></p>
<p>コメント数：<%= post.comments.count %></p>
<p>投稿者：<%= post.user.name %></p>
<p>いいね！：<%= post.get_upvotes.size %></p>
<% end %>


<%= link_to "新規投稿",new_post_path %>

app/views/posts/new.html.erb
<h1>post/new</h1>
<%= render "posts/form" %>

app/views/posts/show.html.erb
<%= image_tag @post.image.url(:medium) %>

<h1>title:<%= @post.title %></h1>
<h1>link:<%= @post.link %></h1>
<h1>description:<%= @post.description %></h1>
<p>=========================</p>
<h1>投稿者名:<%= @post.user.name %></h1>




<p><%= link_to "いいね！", like_post_path(@post), method: :get  %>：<%= @post.get_upvotes.size %></p>
<p><%= link_to "ダメだね!", dislike_post_path(@post),method: :get %>:<%= @post.get_downvotes.size %></p>

<% if @post.user == current_user %>
    <%= link_to "編集",edit_post_path(@post) %>
    <%= link_to "削除",post_path(@post),method: :delete,data:{confirm:"削除してもいですか？"} %>
<% end %>

<h1>
    <p>コメント数：<%= @post.comments.count %></p>
    <p>
        <% @comments.each do |comment| %><br/>
        投稿者：<%= comment.user.name %><br/>
        コメント：<%= comment.content %>
        <% end %>
    </p>
    <p>新規コメント:<%= render "comments/form" %></p>
</h1>